version: '3.8'

# Production overrides for docker-compose.yml
services:
  postgres:
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-your-secure-password}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

  redis:
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD:-your-secure-redis-password}
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  backend:
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:${POSTGRES_PASSWORD:-your-secure-password}@postgres:5432/ai_image_platform
      - REDIS_URL=redis://:${REDIS_PASSWORD:-your-secure-redis-password}@redis:6379/0
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=false
      - ENVIRONMENT=production
      - SENTRY_DSN=${SENTRY_DSN}
    restart: always
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  frontend:
    restart: always
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  nginx:
    restart: always
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  celery_worker:
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:${POSTGRES_PASSWORD:-your-secure-password}@postgres:5432/ai_image_platform
      - REDIS_URL=redis://:${REDIS_PASSWORD:-your-secure-redis-password}@redis:6379/0
      - CELERY_BROKER_URL=redis://:${REDIS_PASSWORD:-your-secure-redis-password}@redis:6379/1
      - CELERY_RESULT_BACKEND=redis://:${REDIS_PASSWORD:-your-secure-redis-password}@redis:6379/2
    restart: always
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

  celery_beat:
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:${POSTGRES_PASSWORD:-your-secure-password}@postgres:5432/ai_image_platform
      - REDIS_URL=redis://:${REDIS_PASSWORD:-your-secure-redis-password}@redis:6379/0
      - CELERY_BROKER_URL=redis://:${REDIS_PASSWORD:-your-secure-redis-password}@redis:6379/1
      - CELERY_RESULT_BACKEND=redis://:${REDIS_PASSWORD:-your-secure-redis-password}@redis:6379/2
    restart: always
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M

  flower:
    environment:
      - CELERY_BROKER_URL=redis://:${REDIS_PASSWORD:-your-secure-redis-password}@redis:6379/1
      - CELERY_RESULT_BACKEND=redis://:${REDIS_PASSWORD:-your-secure-redis-password}@redis:6379/2
    restart: always
    deploy:
      resources:
        limits:
          memory: 256M
        reservations:
          memory: 128M